import { useState } from 'react';
import toast from 'react-hot-toast';

export function useSimulation() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);

  const runSimulation = async (clusterData: any, prompt: string) => {
    setLoading(true);
    try {
      const response = await fetch('/api/simulation/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ clusterData, prompt }),
      });

      if (!response.ok) throw new Error('Simulation failed');
      
      const data = await response.json();
      setResult(data);
      toast.success('Strategy generated by Enerlectra AI');
    } catch (err) {
      toast.error('Could not connect to the Decision Engine');
    } finally {
      setLoading(false);
    }
  };

  return { runSimulation, loading, result, reset: () => setResult(null) };
}